---
- name: Wait for port 22 to come online
  hosts: all
  gather_facts: false
  pre_tasks:
    - name: Waiting for port 22...
      wait_for_connection:
        delay: 5
        connect_timeout: 10
        timeout: 600

    - name: Unzip install
      become: true
      ansible.builtin.apt:
        name: unzip
        state: present

- name: AWS CLI installation
  hosts: all
  become: yes
  roles:
     - deekayen.awscli2

- name: Cron job creation
  hosts: all
  become: true
  tasks:
    - name: Start rule
      ansible.builtin.cron:
        name: "start workstations"
        minute: "{{ start_m }}"
        hour: "{{ start_h }}"
        weekday: "1-5"
        job: 'aws ec2 start-instances --instance-ids $(aws ec2 describe-instances --query "Reservations[].Instances[].InstanceId" --filters "Name=tag:Scheduled,Values=true" "Name=instance-state-name,Values=stopped" --output text)'
        state: present

    - name: Stop rule
      ansible.builtin.cron:
        name: "stop workstations"
        minute: "{{ stop_m }}"
        hour: "{{ stop_h }}"
        weekday: "1-5"
        job: 'aws ec2 stop-instances --instance-ids $(aws ec2 describe-instances --query "Reservations[].Instances[].InstanceId" --filters "Name=tag:Scheduled,Values=true" "Name=instance-state-name,Values=running" --output text)'
        state: present
